const controlCardEvents = {
    SELECT_A_SLIDE: 'CONTROL_CARD/SELECT_A_SLIDE',
    END_SLIDESHOW: 'CONTROL_CARD/END_SLIDESHOW',
    PAUSE_SLIDESHOW: 'CONTROL_CARD/POST_SLIDESHOW',
    PLAY_SLIDESHOW: 'CONTROL_CARD/PLAY_SLIDESHOW'
}

export default controlCardEvents;